package com.corporate.rides.enums;

public enum NotificationType {
    RIDE_BOOKED,
    RIDE_APPROVED,
    RIDE_REJECTED,
    RIDE_SCHEDULED,
    RIDE_RESCHEDULED,
    DRIVER_ASSIGNED,
    DRIVER_ACCEPTED,
    DRIVER_REJECTED,
    VEHICLE_ASSIGNED,
    TRIP_STARTED,
    TRIP_COMPLETED,
    RIDE_COMPLETED,
    TRIP_DELAYED,
    RIDE_CANCELLED,
    LOW_RIDE_RATING,
    DRIVER_FEEDBACK_ESCALATION,
    SYSTEM_ALERT
}
