server:
  port: 8080

spring:
  application:
    name: ride-scheduling-backend

  datasource:
    url: ${DB_URL:jdbc:h2:mem:ridesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}

  sql:
    init:
      mode: never

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.corporate.rides: DEBUG
