# Application Name
spring.application.name=backend

# Supabase PostgreSQL Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://db.gmfzoabwnbynfezortpz.supabase.co:5432/postgres?sslmode=require}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:rIDE_2#0077}

# JPA / Hibernate Configuration
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# SMS Provider Configuration
sms.enabled=false
sms.provider=TWILIO
sms.account.id=
sms.auth.token=
sms.from.number=
